# Static analysis

name: static-analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  static_analysis:
     runs-on: ubuntu-latest
# disabled until the repository is made public
#     permissions:
#       security-events: write
#       actions: read
#       contents: read
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
         with:
            python-version: '3.9'
            
       - name: prepare
         run: pip install flawfinder
       - name: analyse
         run: python -m flawfinder --minlevel=0 --error-level=4 --html -- foundation > results.html
       - name: upload results
         uses: actions/upload-artifact@v3
         with:
           name: flawfinder-results
           path: results.html

# disabled until the repository is made public
#       - name: analyse
#         run: python -m flawfinder --minlevel=0 --sarif -- foundation > results.sarif     
#       - name: upload results
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: results.sarif
#           category: flawfinder
